import { useState, useEffect, useCallback } from "react";
import http from "../lib/http";
import { fmt } from "../lib/dates";

const typeLabel = (id) =>
  ({ annual: "Annual Leave", sick_mc: "Sick Leave (with MC)", sick_nomc: "Sick Leave (without MC)" }[id] ?? id);

const statusChipClass = (r) =>
  r.flagged ? "bg-orange-100 text-orange-800" : "bg-amber-100 text-amber-800";

const recChipClass = (action) =>
  action === "APPROVE"
    ? "bg-emerald-100 text-emerald-800 border-emerald-300"
    : action === "APPROVE_NOTE"
    ? "bg-teal-100 text-teal-800 border-teal-300"
    : "bg-orange-100 text-orange-800 border-orange-300";

const hoursSince = (dt) => Math.max(0, Math.floor((new Date() - new Date(dt)) / (1000 * 60 * 60)));

export default function Approver({ user, setToast }) {
  const isManager = user.role === "MANAGER";
  const [queue, setQueue] = useState([]);
  const [loading, setLoading] = useState(true);

  const load = useCallback(() => {
    setLoading(true);
    http
      .get("/leave/pending")
      .then((res) => setQueue(res.data))
      .finally(() => setLoading(false));
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  const decide = (id, approve, acknowledgeException = false) => {
    http
      .put(`/leave/${id}/decide`, { approve, acknowledgeException })
      .then((res) => {
        const st = res.data.request.status;
        setToast(
          st === "PENDING_MANAGER"
            ? `REQ-${id} routed to the Manager for final approval.`
            : st === "APPROVED"
            ? `REQ-${id} fully approved. Employee notified; balance deducted; calendar updated.`
            : `REQ-${id} rejected. Employee notified.`
        );
        load();
      })
      .catch((err) => setToast(err.response?.data?.message || "Decision failed."));
  };

  return (
    <main className="max-w-6xl mx-auto px-4 py-6 space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <div>
          <h2 className="text-lg font-semibold">
            {isManager ? "Final approvals" : "Team requests"} — {user.team}
          </h2>
          <p className="text-sm text-slate-500">
            {isManager
              ? "Tier 2 of 2. Flagged requests need your explicit coverage-exception approval."
              : "Tier 1 of 2. Your approval routes the request to the Manager."}
          </p>
        </div>
        <span className="text-sm bg-white rounded-full shadow-sm px-3 py-1.5">
          <span className="font-semibold text-teal-800">{queue.length}</span> pending
        </span>
      </div>

      {loading && <p className="text-sm text-slate-400">Loading queue…</p>}

      {!loading && queue.length === 0 && (
        <div className="bg-white rounded-xl shadow-sm p-10 text-center text-slate-400">
          <p className="text-3xl mb-2">✓</p>
          <p className="font-medium text-slate-500">Queue clear</p>
          <p className="text-sm">
            {isManager
              ? "Requests approved by the Supervisor will land here for final decision."
              : "New team requests will appear here with an AI-3 summary card."}
          </p>
        </div>
      )}

      {queue.map((req) => (
        <RequestCard key={req.id} req={req} isManager={isManager} onDecide={decide} />
      ))}
    </main>
  );
}

function RequestCard({ req, isManager, onDecide }) {
  const [ai3, setAi3] = useState(null);
  const [ack, setAck] = useState(false);
  const waitedHrs = hoursSince(req.createdAt);
  const needsAck = isManager && req.flagged;

  // AI-3 summary is generated by the server per request
  useEffect(() => {
    http.get(`/ai/summary/${req.id}`).then((res) => setAi3(res.data));
  }, [req.id]);

  return (
    <div className="bg-white rounded-xl shadow-sm overflow-hidden">
      {/* request header */}
      <div className="p-5 flex flex-wrap items-start justify-between gap-3">
        <div className="flex items-start gap-3">
          <span className="w-10 h-10 rounded-full bg-teal-700 text-white flex items-center justify-center font-semibold shrink-0">
            {req.employee?.initials}
          </span>
          <div>
            <p className="font-semibold">
              {req.employee?.name}{" "}
              <span className="font-normal text-slate-400 text-sm">· REQ-{req.id}</span>
            </p>
            <p className="text-sm text-slate-600">
              {typeLabel(req.leaveType)} · {fmt(req.startDate)}
              {req.endDate !== req.startDate ? ` → ${fmt(req.endDate)}` : ""} · {Number(req.days)}{" "}
              day(s){req.halfDay ? " (half-day)" : ""}
            </p>
            <p className="text-sm text-slate-500 mt-0.5">"{req.reason}"</p>
          </div>
        </div>
        <div className="flex flex-col items-end gap-1.5">
          <span className={`text-xs rounded-full px-2.5 py-1 ${statusChipClass(req)}`}>
            {req.flagged ? "Flagged · special approval" : "Pending"}
          </span>
          <span
            className={`text-xs ${waitedHrs >= 24 ? "text-orange-600 font-medium" : "text-slate-400"}`}
          >
            Waiting {waitedHrs}h{waitedHrs >= 24 ? " · 24h reminder sent" : ""}
          </span>
        </div>
      </div>

      {/* AI-3 summary card */}
      <div className="mx-5 mb-5 rounded-xl border border-teal-200 bg-teal-50 p-4">
        <div className="flex items-center justify-between mb-3">
          <h4 className="font-semibold text-teal-900 text-sm">Approval summary</h4>
          <span className="text-xs bg-teal-200 text-teal-900 rounded-full px-2 py-0.5">
            AI-3 · Approval Assistant
          </span>
        </div>

        {!ai3 ? (
          <p className="text-sm text-teal-800">Generating summary…</p>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {/* pattern */}
            <div className="bg-white rounded-lg p-3">
              <p className="text-xs uppercase tracking-wide text-slate-400 mb-1.5">
                12-month pattern
              </p>
              <ul className="space-y-1.5 text-sm text-slate-700">
                {ai3.patterns.map((p, i) => (
                  <li key={i}>• {p}</li>
                ))}
              </ul>
            </div>

            {/* coverage strip */}
            <div className="bg-white rounded-lg p-3">
              <p className="text-xs uppercase tracking-wide text-slate-400 mb-1.5">
                Team coverage if approved
              </p>
              {ai3.coveragePerDay.length === 0 ? (
                <p className="text-sm text-slate-500">No working days in range.</p>
              ) : (
                <ul className="space-y-1.5">
                  {ai3.coveragePerDay.map((c) => (
                    <li key={c.date} className="flex items-center gap-2 text-sm">
                      <span className="w-20 shrink-0 text-slate-500 text-xs">{fmt(c.date)}</span>
                      <span className="flex gap-0.5">
                        {Array.from({ length: ai3.teamSize }).map((_, i) => (
                          <span
                            key={i}
                            className={`w-3 h-3 rounded-sm ${
                              i < c.present
                                ? "bg-emerald-500"
                                : c.present < ai3.minPresent
                                ? "bg-rose-400"
                                : "bg-slate-300"
                            }`}
                          />
                        ))}
                      </span>
                      <span
                        className={`text-xs ${
                          c.present < ai3.minPresent
                            ? "text-rose-600 font-medium"
                            : "text-slate-500"
                        }`}
                      >
                        {c.present}/{ai3.teamSize} present
                      </span>
                    </li>
                  ))}
                </ul>
              )}
              {ai3.conflicts.length > 0 && (
                <p className="text-xs text-rose-600 mt-2">
                  Also away:{" "}
                  {[...new Set(ai3.conflicts.flatMap((c) => c.offNames))].join(", ")}
                </p>
              )}
            </div>

            {/* recommendation */}
            <div className="bg-white rounded-lg p-3 flex flex-col">
              <p className="text-xs uppercase tracking-wide text-slate-400 mb-1.5">
                Recommendation
              </p>
              <span
                className={`self-start text-xs font-medium rounded-full border px-2.5 py-1 mb-2 ${recChipClass(
                  ai3.recommendation.action
                )}`}
              >
                {ai3.recommendation.label}
              </span>
              <p className="text-sm text-slate-700">{ai3.recommendation.rationale}</p>
              <p className="text-xs text-slate-400 mt-auto pt-2">
                Advisory only — the decision is always yours (no auto-approval).
              </p>
            </div>
          </div>
        )}
      </div>

      {/* audit timeline */}
      <div className="mx-5 mb-4 text-xs text-slate-400 space-y-0.5">
        {(req.AuditLogs || []).map((t, i) => (
          <p key={i}>
            {new Date(t.createdAt).toLocaleString("en-SG", {
              day: "numeric",
              month: "short",
              hour: "2-digit",
              minute: "2-digit",
            })}{" "}
            — {t.action} ({t.actorName})
          </p>
        ))}
      </div>

      {/* actions */}
      <div className="px-5 pb-5 flex flex-wrap items-center gap-3">
        {needsAck && (
          <label className="flex items-center gap-2 text-sm text-orange-800 bg-orange-50 border border-orange-200 rounded-lg px-3 py-2 w-full sm:w-auto">
            <input
              type="checkbox"
              checked={ack}
              onChange={(e) => setAck(e.target.checked)}
              className="w-4 h-4 accent-orange-600"
            />
            I explicitly approve this coverage exception
          </label>
        )}
        <button
          onClick={() => onDecide(req.id, true, ack)}
          disabled={needsAck && !ack}
          className="bg-teal-700 hover:bg-teal-800 disabled:bg-slate-300 text-white text-sm font-medium rounded-lg px-5 py-2"
        >
          {isManager
            ? req.flagged
              ? "Approve exception (final)"
              : "Approve (final)"
            : req.flagged
            ? "Endorse & escalate to Manager"
            : "Approve → route to Manager"}
        </button>
        <button
          onClick={() => onDecide(req.id, false)}
          className="bg-white border border-rose-300 text-rose-600 hover:bg-rose-50 text-sm font-medium rounded-lg px-5 py-2"
        >
          Reject
        </button>
      </div>
    </div>
  );
}
